version: '3'
services:
    # Container for nginx
    nginx:
        image: nginx:latest
        container_name: nginxtruckpag
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - truckpag_net

    # Container for Laravel
    app:
        build:
            context: .
            dockerfile: Dockerfile
        user: "${USER_ID}:${GROUP_ID}"
        volumes:
            - ./:/var/www/html
        environment:
            - "DB_HOST=dbtruckpag"
            - "DB_PORT=3306"
            - "DB_DATABASE=truckpagdb"
            - "DB_USERNAME=truckpagroot"
            - "DB_PASSWORD=truckpagsecret132"
        command: bash -c "composer install --no-interaction \
            && php artisan key:generate \
            && php artisan config:cache \
            && php artisan route:cache \
            && php artisan view:cache \
            && chmod -R 777 storage \
            && chown -R www-data:www-data /var/www/html/storage \
            && php-fpm"
        depends_on:
            - dbtruckpag
        networks:
            - truckpag_net

    # Container for MariaDB
    dbtruckpag:
        image: mariadb:10.6
        restart: always
        ports:
            - "3313:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=truckpagdb
            - MYSQL_USER=truckpagroot
            - MYSQL_PASSWORD=truckpagsecret132
        networks:
            - truckpag_net

volumes:
    truckpag-backend:

networks:
    truckpag_net:
